### PR TITLE
Finished the logic for populating weekly view. Weekly css also fixed

### LINKED ISSUE #230: Weekly view follow-up
There is logic left unfinished regarding to the days of the week on weekly page. Per Jordan's suggestions, the weekly box should be aligned with the calendar starting on the same line
## Detailed Description
We need to calculate the offset for populating the weekly page after getting the entries that are in the same week. We need more unit tests on this.
## Context
Better UI
Accurate fetch and display
## Possible Implementation
DateConverter should be enough
## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows PC

### PR DESCRIPTION
**Pull request by yuzilyu**

### CODE REVIEW

File: source/javascript/src/weekly.js [hunk 1]
```diff
@@ -69,13 +82,20 @@ function getLogInfoAsJSON (cb) {
...
-  let i = 6
   const week = document.getElementById('weekly-div')
+  // create a DateConverter object
+  const current = new DateConverter(Date.now())
+  // Use a new instance of Date to fetch the day of the week of today
+  const today = new Date()
+  const todayDays = today.getDay()
   entryArr.forEach((entry) => {
+    // calculate the offset between today's day and the entry's day
+    const offSet = current.getDaysFromTimeStamp(Date.now()) - current.getDaysFromTimeStamp(entry.properties.date.time)
```
Comment (NoahT) [inline source/javascript/src/weekly.js:93]: No feedback here, just wanted to say great job on this part 👍

File: source/html/index.html [hunk 2]
```diff
@@ -125,6 +125,15 @@ <h1 id="bujo-header">R.I.V.E.R BuJo</h1>
 
     <footer>
 
+        <!-- <details>
```
Comment (NoahT) [inline source/html/index.html:128]: As a group we may want to start considering removing commented out code in our PR's next sprint (it may help graders know what has been finalized in our code)

**Review by NoahT — APPROVED** [review]
LGTM
