### PR TITLE
Delete TODO's and Styleguide fixes

### LINKED ISSUE #373: Remove TODO markers
## Detailed Description
We should remove all the TODO markers in all the source files.

## Context
We are starting to wrap up the project and making our final changes to the bullet journal, so we should remove all the TODO's.

### PR DESCRIPTION
**Pull request by thanhtong010**
Deleted the TODO's as described in #373 and misc. comments in all the js files. Also updated some files to fix the tabs to match the styleguide.

### CODE REVIEW

File: source/javascript/src/weekly.js [hunk 1]
```diff
@@ -123,10 +131,11 @@ document.addEventListener('DOMContentLoaded', (event) => {
 })
 
 /**
- * @author Katherine Baker <klbaker@ucsd.edu>, and Yuzi Lyu <>, Noah Teshima <nteshima@ucsd.edu>
+ * @author Katherine Baker <klbaker@ucsd.edu>
```
Comment (NoahT) [inline source/javascript/src/weekly.js:134]: Good catch; this will show up better with JSDocs

**Review by NoahT — APPROVED** [review]
LGTM. Thank you for cleaning up the existing code 🙌
