### PR TITLE
Dynamic placeholder text on Daily Log page

### LINKED ISSUE #340: Daily Log page styling
On smaller screens the layout overflows beyond the right edge of the screen.

**To Reproduce**
1. Go to Index Page on a smaller monitor

**Expected behavior**
Page layout resizes to fit content onto smaller screen.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 91.0.4472.77

**Additional context**
Possibly has to do with the grid layout for the `id="textbox` form element.

### LINKED ISSUE #354: Change default text for notes/tasks/events in daily log
**Describe the bug**
This is not necessarily a bug but more so a change that would make more sense for the user. Currently, when the user makes a task/note/event/reflection for the daily log, the default text is always "Input your todo here". However, that does not make sense when the entry type is a reflection for example. It could be better if we customize them for reflection and event maybe (just simple fix to "Input your reflection here").

**To Reproduce**
1. Go to daily log entry.
2. Click on Reflection/Note/Event/Task
3. See the default text.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by will-chung**
Text input on Daily Log page no longer always shows "Input your todo here", instead changing depending on the entry type that is selected. Also minor changes to the radio menu container.

### CODE REVIEW

File: source/javascript/src/components/tag.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const template = document.createElement('template')
 
 template.innerHTML = `
   <style>
-    @import '/cse110-w21-group7/css/font/bootstrap-icons.css';
+    @import '/cse110-SP21-group7/css/font/bootstrap-icons.css';
```
Comment (NoahT) [inline source/javascript/src/components/tag.js:9]: Good catch! This will probably fix the issue too 👍

File: source/javascript/src/utils/Router.js [hunk 2]
```diff
@@ -1,4 +1,4 @@
-const prod = true
+const prod = false
```
Comment (NoahT) [inline source/javascript/src/utils/Router.js]: Before we push this let's change this flag to true so the routing is correct

**Review by NoahT — CHANGES_REQUESTED** [review]

**Review by NoahT — APPROVED** [review]
LGTM

**Review by thanhtong010 — COMMENTED** [review]
Looks good! :)
