### PR TITLE
Multiple UI fixes

### LINKED ISSUE #260: Collection-edit page UI improvement
The entry input field UI is very inconsistent with the rest
## Detailed Description
To improve the UI of the web app, I will be working on making the input field on collection-edit page more consistent with the color scheme and refactor the size of the input field
## Context
Per Jordan's suggestion 
## Possible Implementation
Color change, more css
## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows PC

### LINKED ISSUE #261: Collection edit page video upload size bug
There is currently a bug with uploading the video. The size of the video does not fit the window. Not sure if the same issue applies to image upload
## Detailed Description
Enforcing a div and making sure the video file is coherent with the size
## Context
uploading images and videos could potentially break the UI so making sure this bug gets resolved is importnat
## Possible Implementation
Need to look at css and js
## Your Environment
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows PC

### LINKED ISSUE #263: Header consistency
Currently the header and title section of each page is not consistent, they all have their different size and css code
## Detailed Description
I am going to make the css code more consistent with the headers on each page. Daily log is not included in this issue
## Context
For better consistency
## Possible Implementation
consistent css code
## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows PC

### PR DESCRIPTION
**Pull request by yuzilyu**
Header is more consistent throughout the page
Video size in collection-edit is fixed
collection-edit UI improvement, I still haven't finished the top half but the bottom half is basically done
Changed the logic of chevron, now when the content is loaded on collection edit, the media gallery will not show unless user clicks on chevron
Changed the position of the input button
Added the hover event listener for the trashcan button on images and videos

### CODE REVIEW

**Comment by yuzilyu** [comment]
#260 I am going to close this issue for now, and create a new one that specifically focus the top half of the page

File: source/javascript/src/weekly.js [hunk 1]
```diff
@@ -66,13 +66,16 @@ function populateDayColumns (weeklyItems) {
...
   // Use a new instance of Date to fetch the day of the week of today
   const today = new DateConverter()
-  const todayDays = today.getDay()
+  let todayDays = today.getDay()
   weeklyItems.forEach((entry) => {
     // calculate the offset between today's day and the entry's day
     const offSet = current.getDaysFromTimeStamp(Date.now()) - current.getDaysFromTimeStamp(entry.properties.date.time)
     const currentDay = new DateConverter(Number(entry.properties.date.time))
     // apply the offset to get the index
-    const index = todayDays + 6 - offSet
```
Comment (NoahT) [inline source/javascript/src/weekly.js:75]: Depending on the order in which we merge #264 and #262, this section may create merge conflicts.
We should also have a quick meeting on Tuesday around standup to discuss what the best approach would be here  (Sunday-Saturday vs. Monday-Sunday)

**Review by NoahT — APPROVED** [review]
LGTM (one comment we should address though with regards to Tuesday's meeting)
