### PR TITLE
Fixed issue with fuzzy search not working for long strings.

### LINKED ISSUE #352: Search functionality has different results
**Describe the bug**
For the Search Feature, sometimes typing in a search will give me different results. For example, I have the log with the task "Walk dog" and event "COGS101A Midterm". When I type "Walk", it just gives me the result "Walk dog". However, when I type "dog", it has both "Walk dog" and "COGS101A Midterm" on the daily log result. There are also some issues where I type in keywords but the expected result does not show up. Will attach pictures below so it's easier to see.

**To Reproduce**
1. Go to current daily log.
2. Add a task and another event.
3. Go to the search bar.
4. Search for that tasks and/or event separate, using different keywords to search each time.
5. See error

**Expected behavior**
I'm not sure what the expected result is for the search feature (if it should only show the event/task/note w/ the keyword in the daily log or if it should show all the events/notes/tasks in the daily log, but will display the daily log(s) that have the keywords).

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by NoahT**
Fuse.js apparently uses location-based fuzzy search when given a pattern, which tells Fuse.js where to look for the pattern. However, this parameter can easily be disabled with a config change. Resolves #352

### CODE REVIEW

File: source/javascript/src/components/WeeklyViewItem.js [hunk 1]
```diff
@@ -73,40 +70,23 @@ background: linear-gradient(335deg, rgba(247,240,63,1) 0%, rgba(254,255,156,1) 1
...
     const tasks = this._entry.properties.tasks
-    // console.log(tasks);
     const notes = this._entry.properties.notes
-    // console.log(notes);
     const events = this._entry.properties.events
-    // console.log(events);
     const reflection = this._entry.properties.reflection
-    // console.log(reflection);
 
-    reflection.forEach((reflection, index) => {
```
Comment (NoahT) [inline source/javascript/src/components/WeeklyViewItem.js:84]: @will-chung Just a little clean up ~(:

**Review by will-chung — APPROVED** [review]
Looks good!
